version: '3'
services:
  linnaeus:
    image: "naturalis/linnaeus:0.0.1"
    env_file:
      - .env
    ports:
     - "8080:80"
    volumes:
     - "/data/linnaeus/www:/var/www/html"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=linnaeusng_backend"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:linnaeus.naturalis.nl"
  db:
    image: "mysql"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
    networks:
      - default
    volumes:
    - "/data/linnaeus/initdb:/docker-entrypoint-initdb.d"
    - "/data/linnaeus/db:/var/lib/mysql"

# run docker network create web before
networks:
  web:
    external: true
