version: '3'
services:
  linnaeus:
    image: "naturalis/linnaeus:0.0.1"
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - "80:80"
    volumes:
     - "/data/linnaeus/www:/var/www/html"
     - "/data/linnaeus/apachelog:/var/log/apache2"
    networks:
      - default
  db:
    image: "mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
    networks:
      - default
    volumes:
    - "/data/linnaeus/mysqlconf:/etc/mysql/conf.d"
    - "/data/linnaeus/initdb:/docker-entrypoint-initdb.d"
    - "/data/linnaeus/mysqllog:/var/log/mysql"
    - "${BASE_PATH:-/data/linnaeus/db}:/var/lib/mysql"


