version: '3'
services:
  linnaeus:
    image: "naturalis/linnaeus:0.0.1"
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - "80:80"
    volumes:
     - ${BASE_PATH:-/data}/linnaeus/www:/var/www/html
     - ${BASE_PATH:-/data}/linnaeus/apachelog:/var/log/apache2
    networks:
      - default
  db:
    image: "mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
    networks:
      - default
    ports:
      - "3307:3306"
    volumes:
        - ${BASE_PATH:-/data}/linnaeus/initdb:/docker-entrypoint-initdb.d
        - ${BASE_PATH:-/data}/linnaeus/db:/var/lib/mysql
        - ./my.conf.d:/etc/mysql/conf.d

