version: '3'
services:
  linnaeus:
    image: "naturalis/linnaeus:0.0.1"
    env_file:
      - .env
    ports:
     - "80:80"
    volumes:
     - "/data/linnaeus/www:/var/www/html"
    networks:
      - default
  db:
    image: "mysql"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
    networks:
      - default
    volumes:
    - "/data/linnaeus/initdb:/docker-entrypoint-initdb.d"
    - "/data/linnaeus/db:/var/lib/mysql"


